function modelPath = build_multibody_model(openAfterBuild)
%BUILD_MULTIBODY_MODEL Build a parameterized Simscape Multibody model.
% The model reproduces the ideal assumptions used in the analytical model:
% prescribed alpha and beta, massless links (numerically negligible visual
% solids), a point mass at E, and a free revolute coordinate psi.

arguments
    openAfterBuild (1,1) logical = true
end

scriptDirectory = fileparts(mfilename('fullpath'));
matlabRoot = fileparts(scriptDirectory);
addpath(matlabRoot);

p = rotpend.defaultParameters();
viz.armThickness = 0.025;
viz.diskThickness = 0.025;
viz.diskRadius = max(p.r + 0.04, 0.08);
viz.rodRadius = 0.006;
viz.massRadius = 0.025;
viz.negligibleMass = 1e-9;
viz.negligibleInertia = [1e-12 1e-12 1e-12];

modelName = 'rotating_pendulum_multibody';
modelPath = fullfile(scriptDirectory, modelName + ".slx");

load_system('simulink');
load_system('sm_lib');
load_system('nesl_utility');
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);

set_param(modelName, ...
    'SolverType', 'Variable-step', ...
    'Solver', 'ode15s', ...
    'StopTime', '20', ...
    'RelTol', '1e-8', ...
    'AbsTol', '1e-10', ...
    'MaxStep', '0.005', ...
    'ReturnWorkspaceOutputs', 'on');

workspace = get_param(modelName, 'ModelWorkspace');
assignin(workspace, 'p', p);
assignin(workspace, 'viz', viz);

% Global physical configuration.
addLibraryBlock('sm_lib', 'World Frame', modelName + "/World", [35 55 85 105]);
addLibraryBlock('sm_lib', 'Mechanism Configuration', ...
    modelName + "/Gravidade", [35 135 95 185]);
set_param(modelName + "/Gravidade", 'GravityVector', '[0 0 -p.g]');
addLibraryBlock('nesl_utility', 'Solver Configuration', ...
    modelName + "/Solver Configuration", [35 215 95 265]);

% Fixed geometry O -> A and base visualization.
addRigidTransform(modelName, 'RT O-A', [0 0 0], [0 0 0], [150 65 220 115]);
set_param(modelName + "/RT O-A", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 0 p.a]');
addRigidTransform(modelName, 'RT coluna centro', [0 0 0], [0 0 0], ...
    [140 150 220 200]);
set_param(modelName + "/RT coluna centro", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 0 p.a/2]');
addLibraryBlock('sm_lib', 'Cylindrical Solid', modelName + "/Coluna visual", ...
    [260 150 350 200]);
configureCylinder(modelName + "/Coluna visual", ...
    'viz.armThickness', 'p.a', '[0.35 0.38 0.42]');

% Joint alpha and prescribed angular motion.
addLibraryBlock('sm_lib', 'Revolute Joint', modelName + "/Junta alpha", ...
    [270 45 350 115]);
set_param(modelName + "/Junta alpha", ...
    'MotionActuationMode', 'InputMotion', ...
    'TorqueActuationMode', 'ComputedTorque', ...
    'SensePosition', 'on', 'SenseVelocity', 'on');
addPrescribedAngle(modelName, 'alpha', 'p.alpha0', 'p.alphaRate', ...
    [120 325], [390 45]);

% Arm A-B and translation to C.
addRigidTransform(modelName, 'RT braco centro', [0 0 0], [0 0 0], ...
    [410 145 490 195]);
set_param(modelName + "/RT braco centro", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[p.b/2 0 0]');
addLibraryBlock('sm_lib', 'Brick Solid', modelName + "/Braco visual", ...
    [530 145 620 195]);
configureBrick(modelName + "/Braco visual", ...
    '[p.b viz.armThickness viz.armThickness]', '[0.15 0.38 0.75]');

addRigidTransform(modelName, 'RT A-B', [0 0 0], [0 0 0], [410 45 490 95]);
set_param(modelName + "/RT A-B", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[p.b 0 0]');
addRigidTransform(modelName, 'RT B-C', [0 0 0], [0 0 0], [530 45 610 95]);
set_param(modelName + "/RT B-C", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 0 p.c]');

% Joint beta and prescribed relative motion.
addLibraryBlock('sm_lib', 'Revolute Joint', modelName + "/Junta beta", ...
    [655 35 735 105]);
set_param(modelName + "/Junta beta", ...
    'MotionActuationMode', 'InputMotion', ...
    'TorqueActuationMode', 'ComputedTorque', ...
    'SensePosition', 'on', 'SenseVelocity', 'on');
addPrescribedAngle(modelName, 'beta', 'p.beta0', 'p.betaRate', ...
    [505 325], [780 35]);

% Disk and the offset C-D = [0 r h] expressed in B2.
addLibraryBlock('sm_lib', 'Cylindrical Solid', modelName + "/Disco visual", ...
    [790 145 885 195]);
configureCylinder(modelName + "/Disco visual", ...
    'viz.diskRadius', 'viz.diskThickness', '[0.72 0.22 0.18]');

addRigidTransform(modelName, 'RT suporte radial centro', [0 0 0], [0 0 0], ...
    [790 230 885 280]);
set_param(modelName + "/RT suporte radial centro", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 p.r/2 0]');
addLibraryBlock('sm_lib', 'Brick Solid', modelName + "/Suporte radial visual", ...
    [925 230 1025 280]);
configureBrick(modelName + "/Suporte radial visual", ...
    '[viz.armThickness p.r viz.armThickness]', '[0.80 0.52 0.16]');

addRigidTransform(modelName, 'RT suporte vertical centro', [0 0 0], [0 0 0], ...
    [790 305 885 355]);
set_param(modelName + "/RT suporte vertical centro", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 p.r p.h/2]');
addLibraryBlock('sm_lib', 'Brick Solid', modelName + "/Suporte vertical visual", ...
    [925 305 1025 355]);
configureBrick(modelName + "/Suporte vertical visual", ...
    '[viz.armThickness viz.armThickness p.h]', '[0.80 0.52 0.16]');

addRigidTransform(modelName, 'RT C-D', [0 0 0], [0 0 0], [790 45 875 95]);
set_param(modelName + "/RT C-D", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 p.r p.h]');

% Permutation: xJ=y2, yJ=z2, zJ=x2. The revolute Z axis is therefore X2.
addRigidTransform(modelName, 'RT eixo psi', [0 0 0], [0 0 0], [915 45 1000 95]);
set_param(modelName + "/RT eixo psi", ...
    'RotationMethod', 'RotationMatrix', ...
    'RotationMatrix', '[0 0 1; 1 0 0; 0 1 0]');

% Free pendulum joint with initial targets and sensing.
addLibraryBlock('sm_lib', 'Revolute Joint', modelName + "/Junta psi", ...
    [1045 25 1130 115]);
set_param(modelName + "/Junta psi", ...
    'PositionTargetSpecify', 'on', ...
    'PositionTargetValue', 'p.psi0', ...
    'PositionTargetValueUnits', 'rad', ...
    'PositionTargetPriority', 'High', ...
    'VelocityTargetSpecify', 'on', ...
    'VelocityTargetValue', 'p.psiRate0', ...
    'VelocityTargetValueUnits', 'rad/s', ...
    'VelocityTargetPriority', 'High', ...
    'SensePosition', 'on', ...
    'SenseVelocity', 'on', ...
    'SenseAcceleration', 'on', ...
    'SenseConstraintForce', 'on');

% Rod visual is aligned with -Y of the joint follower frame.
addRigidTransform(modelName, 'RT haste centro', [0 0 0], [0 0 0], ...
    [1175 145 1265 195]);
set_param(modelName + "/RT haste centro", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 -p.l/2 0]', ...
    'RotationMethod', 'StandardAxis', ...
    'RotationStandardAxis', '+X', ...
    'RotationAngle', '90', ...
    'RotationAngleUnits', 'deg');
addLibraryBlock('sm_lib', 'Cylindrical Solid', modelName + "/Haste visual", ...
    [1305 145 1395 195]);
configureCylinder(modelName + "/Haste visual", ...
    'viz.rodRadius', 'p.l', '[0.25 0.55 0.82]');

addRigidTransform(modelName, 'RT D-E', [0 0 0], [0 0 0], [1175 35 1265 85]);
set_param(modelName + "/RT D-E", ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', '[0 -p.l 0]');
addLibraryBlock('sm_lib', 'Inertia', modelName + "/Massa pontual E", ...
    [1310 20 1400 70]);
set_param(modelName + "/Massa pontual E", ...
    'InertiaType', 'PointMass', 'Mass', 'p.m', 'MassUnits', 'kg', ...
    'GraphicType', 'Marker', 'MarkerShape', 'Sphere', ...
    'MarkerSize', 'viz.massRadius', ...
    'MarkerSize_conf', 'compiletime', ...
    'GraphicDiffuseColor', '[0.85 0.12 0.12]');

% World-to-E sensor provides the absolute 3-D trajectory.
addLibraryBlock('sm_lib', 'Transform Sensor', modelName + "/Sensor posicao E", ...
    [1190 245 1280 315]);
set_param(modelName + "/Sensor posicao E", ...
    'MeasurementFrame', 'World', 'SenseXYZ', 'on');

% Output converters and sinks.
addPhysicalOutput(modelName, 'psi', 'rad', 'mbPsi', [1180 390]);
addPhysicalOutput(modelName, 'psiDot', 'rad/s', 'mbPsiDot', [1180 450]);
addPhysicalOutput(modelName, 'psiDDot', 'rad/s^2', 'mbPsiDDot', [1180 510]);
addPhysicalOutput(modelName, 'forca D', 'N', 'mbJointForce', [1180 570]);
addPhysicalOutput(modelName, 'posicao E', 'm', 'mbPositionE', [1320 270]);
addPhysicalOutput(modelName, 'alpha medido', 'rad', 'mbAlpha', [405 230]);
addPhysicalOutput(modelName, 'beta medido', 'rad', 'mbBeta', [785 390]);

add_block('simulink/Signal Routing/Mux', modelName + "/Mux estados", ...
    'Inputs', '3', 'Position', [1510 390 1515 510]);
add_block('simulink/Sinks/Scope', modelName + "/Scope estados Multibody", ...
    'Position', [1560 420 1625 480]);
add_block('simulink/Sinks/Scope', modelName + "/Scope posicao E", ...
    'Position', [1510 270 1575 320]);

% Physical frame network.
connectFrame(modelName, 'World', 'R', 1, 'Gravidade', 'R', 1);
connectFrame(modelName, 'World', 'R', 1, 'Solver Configuration', 'R', 1);
connectFrame(modelName, 'World', 'R', 1, 'RT O-A', 'L', 1);
connectFrame(modelName, 'World', 'R', 1, 'RT coluna centro', 'L', 1);
connectFrame(modelName, 'RT coluna centro', 'R', 1, 'Coluna visual', 'R', 1);
connectFrame(modelName, 'RT O-A', 'R', 1, 'Junta alpha', 'L', 1);

connectFrame(modelName, 'Junta alpha', 'R', 1, 'RT A-B', 'L', 1);
connectFrame(modelName, 'Junta alpha', 'R', 1, 'RT braco centro', 'L', 1);
connectFrame(modelName, 'RT braco centro', 'R', 1, 'Braco visual', 'R', 1);
connectFrame(modelName, 'RT A-B', 'R', 1, 'RT B-C', 'L', 1);
connectFrame(modelName, 'RT B-C', 'R', 1, 'Junta beta', 'L', 1);

connectFrame(modelName, 'Junta beta', 'R', 1, 'Disco visual', 'R', 1);
connectFrame(modelName, 'Junta beta', 'R', 1, 'RT suporte radial centro', 'L', 1);
connectFrame(modelName, 'RT suporte radial centro', 'R', 1, ...
    'Suporte radial visual', 'R', 1);
connectFrame(modelName, 'Junta beta', 'R', 1, 'RT suporte vertical centro', 'L', 1);
connectFrame(modelName, 'RT suporte vertical centro', 'R', 1, ...
    'Suporte vertical visual', 'R', 1);
connectFrame(modelName, 'Junta beta', 'R', 1, 'RT C-D', 'L', 1);
connectFrame(modelName, 'RT C-D', 'R', 1, 'RT eixo psi', 'L', 1);
connectFrame(modelName, 'RT eixo psi', 'R', 1, 'Junta psi', 'L', 1);

connectFrame(modelName, 'Junta psi', 'R', 1, 'RT haste centro', 'L', 1);
connectFrame(modelName, 'RT haste centro', 'R', 1, 'Haste visual', 'R', 1);
connectFrame(modelName, 'Junta psi', 'R', 1, 'RT D-E', 'L', 1);
connectFrame(modelName, 'RT D-E', 'R', 1, 'Massa pontual E', 'R', 1);
connectFrame(modelName, 'World', 'R', 1, 'Sensor posicao E', 'L', 1);
connectFrame(modelName, 'RT D-E', 'R', 1, 'Sensor posicao E', 'R', 1);

% Physical signals: motion inputs and measured outputs.
connectFrame(modelName, 'alpha Simulink-PS', 'R', 1, 'Junta alpha', 'L', 2);
connectFrame(modelName, 'beta Simulink-PS', 'R', 1, 'Junta beta', 'L', 2);

connectFrame(modelName, 'Junta alpha', 'R', 2, 'alpha medido PS-Simulink', 'L', 1);
connectFrame(modelName, 'Junta beta', 'R', 2, 'beta medido PS-Simulink', 'L', 1);
connectFrame(modelName, 'Junta psi', 'R', 2, 'psi PS-Simulink', 'L', 1);
connectFrame(modelName, 'Junta psi', 'R', 3, 'psiDot PS-Simulink', 'L', 1);
connectFrame(modelName, 'Junta psi', 'R', 4, 'psiDDot PS-Simulink', 'L', 1);
connectFrame(modelName, 'Junta psi', 'R', 5, 'forca D PS-Simulink', 'L', 1);
connectFrame(modelName, 'Sensor posicao E', 'R', 2, ...
    'posicao E PS-Simulink', 'L', 1);

% Simulink signal routing for scopes.
add_line(modelName, 'psi PS-Simulink/1', 'Mux estados/1', 'autorouting', 'on');
add_line(modelName, 'psiDot PS-Simulink/1', 'Mux estados/2', 'autorouting', 'on');
add_line(modelName, 'psiDDot PS-Simulink/1', 'Mux estados/3', 'autorouting', 'on');
add_line(modelName, 'Mux estados/1', 'Scope estados Multibody/1', 'autorouting', 'on');
add_line(modelName, 'posicao E PS-Simulink/1', 'Scope posicao E/1', 'autorouting', 'on');

% Explanatory notes.
addAnnotation(modelName, ...
    'alpha e beta: movimentos prescritos; psi: coordenada dinamica livre', ...
    [265 5 800 25], 'blue');
addAnnotation(modelName, ...
    'C-D = r*j2 + h*k2; a altura de D em relacao a B e c+h', ...
    [770 365 1190 385], 'darkGreen');
addAnnotation(modelName, ...
    'O ponto E possui massa p.m; os solidos coloridos tem massa numericamente desprezivel', ...
    [1040 700 1620 720], 'red');

set_param(modelName, 'ZoomFactor', 'FitSystem');
save_system(modelName, modelPath);

if openAfterBuild
    open_system(modelName);
else
    close_system(modelName, 0);
end
end

function addLibraryBlock(library, blockName, destination, position)
matches = find_system(library, 'LookUnderMasks', 'all', ...
    'FollowLinks', 'on', 'Name', blockName);
assert(~isempty(matches), 'multibody:MissingLibraryBlock', ...
    'Library block not found: %s/%s', library, blockName);
add_block(matches{1}, destination, 'Position', position);
end

function addRigidTransform(modelName, name, ~, ~, position)
addLibraryBlock('sm_lib', 'Rigid Transform', modelName + "/" + name, position);
end

function configureBrick(block, dimensions, color)
set_param(block, ...
    'BrickDimensions', dimensions, ...
    'InertiaType', 'Custom', ...
    'Mass', 'viz.negligibleMass', ...
    'MomentsOfInertia', 'viz.negligibleInertia', ...
    'ProductsOfInertia', '[0 0 0]', ...
    'GraphicDiffuseColor', color);
end

function configureCylinder(block, radius, length, color)
set_param(block, ...
    'CylinderRadius', radius, ...
    'CylinderLength', length, ...
    'InertiaType', 'Custom', ...
    'Mass', 'viz.negligibleMass', ...
    'MomentsOfInertia', 'viz.negligibleInertia', ...
    'ProductsOfInertia', '[0 0 0]', ...
    'GraphicDiffuseColor', color);
end

function addPrescribedAngle(modelName, prefix, offset, rate, sourcePosition, converterPosition)
clock = modelName + "/" + prefix + " Clock";
gain = modelName + "/" + prefix + " rate";
constant = modelName + "/" + prefix + "0";
sumBlock = modelName + "/" + prefix + "(t)";
converter = modelName + "/" + prefix + " Simulink-PS";

x = sourcePosition(1);
y = sourcePosition(2);
add_block('simulink/Sources/Clock', clock, 'Position', [x y x+30 y+20]);
add_block('simulink/Math Operations/Gain', gain, 'Gain', rate, ...
    'Position', [x+55 y-10 x+120 y+30]);
add_block('simulink/Sources/Constant', constant, 'Value', offset, ...
    'Position', [x+55 y+50 x+120 y+80]);
add_block('simulink/Math Operations/Sum', sumBlock, 'Inputs', '++', ...
    'Position', [x+150 y+5 x+180 y+65]);
addLibraryBlock('nesl_utility', 'Simulink-PS Converter', converter, ...
    [converterPosition(1) converterPosition(2) ...
     converterPosition(1)+75 converterPosition(2)+45]);
set_param(converter, 'Unit', 'rad', ...
    'FilteringAndDerivatives', 'provide', ...
    'UdotUserProvided', '2');
velocity = modelName + "/" + prefix + " velocidade";
acceleration = modelName + "/" + prefix + " aceleracao";
add_block('simulink/Sources/Constant', velocity, 'Value', rate, ...
    'Position', [converterPosition(1)-105 converterPosition(2)+55 ...
                 converterPosition(1)-40 converterPosition(2)+85]);
add_block('simulink/Sources/Constant', acceleration, 'Value', '0', ...
    'Position', [converterPosition(1)-105 converterPosition(2)+100 ...
                 converterPosition(1)-40 converterPosition(2)+130]);
add_line(modelName, prefix + " Clock/1", prefix + " rate/1", 'autorouting', 'on');
add_line(modelName, prefix + " rate/1", prefix + "(t)/1", 'autorouting', 'on');
add_line(modelName, prefix + "0/1", prefix + "(t)/2", 'autorouting', 'on');
add_line(modelName, prefix + "(t)/1", prefix + " Simulink-PS/1", 'autorouting', 'on');
add_line(modelName, prefix + " velocidade/1", prefix + " Simulink-PS/2", ...
    'autorouting', 'on');
add_line(modelName, prefix + " aceleracao/1", prefix + " Simulink-PS/3", ...
    'autorouting', 'on');
end

function addPhysicalOutput(modelName, prefix, unit, variable, position)
converter = modelName + "/" + prefix + " PS-Simulink";
sink = modelName + "/Salvar " + prefix;
addLibraryBlock('nesl_utility', 'PS-Simulink Converter', converter, ...
    [position(1) position(2) position(1)+85 position(2)+40]);
set_param(converter, 'Unit', unit);
add_block('simulink/Sinks/To Workspace', sink, ...
    'VariableName', variable, 'SaveFormat', 'Timeseries', ...
    'Position', [position(1)+135 position(2) position(1)+235 position(2)+40]);
add_line(modelName, prefix + " PS-Simulink/1", "Salvar " + prefix + "/1", ...
    'autorouting', 'on');
end

function connectFrame(modelName, blockA, sideA, indexA, blockB, sideB, indexB)
portsA = get_param(modelName + "/" + blockA, 'PortHandles');
portsB = get_param(modelName + "/" + blockB, 'PortHandles');
fieldA = sideA + "Conn";
fieldB = sideB + "Conn";
add_line(modelName, portsA.(fieldA)(indexA), portsB.(fieldB)(indexB), ...
    'autorouting', 'on');
end

function addAnnotation(modelName, text, position, color)
annotation = Simulink.Annotation(modelName, text);
annotation.Position = position;
annotation.ForegroundColor = color;
end
