function validateParameters(p)
%VALIDATEPARAMETERS Check model inputs before numerical integration.

required = {'a','b','c','r','h','l','m','g','alphaProfile','betaProfile', ...
    'motionFunction','psi0','psiRate0','damping','appliedTorque'};
missing = required(~isfield(p, required));
assert(isempty(missing), 'rotpend:MissingParameter', ...
    'Missing parameter(s): %s', strjoin(missing, ', '));

finiteScalars = {'a','b','c','r','h','l','m','g','psi0','psiRate0','damping'};
for k = 1:numel(finiteScalars)
    value = p.(finiteScalars{k});
    assert(isnumeric(value) && isscalar(value) && isfinite(value), ...
        'rotpend:InvalidParameter', '%s must be a finite scalar.', finiteScalars{k});
end

assert(p.a >= 0 && p.b > 0 && p.c >= 0 && p.r >= 0 && p.h >= 0 && p.l > 0, ...
    'rotpend:InvalidGeometry', ...
    'Lengths must satisfy a,c,r,h >= 0 and b,l > 0.');
assert(p.m > 0 && p.g > 0, 'rotpend:InvalidPhysicalParameter', ...
    'Mass and gravitational acceleration must be positive.');
assert(p.damping >= 0, 'rotpend:InvalidDamping', ...
    'Damping must be nonnegative.');
assert(isa(p.appliedTorque, 'function_handle'), 'rotpend:InvalidTorque', ...
    'appliedTorque must be a function handle @(t,x).');
assert(isempty(p.motionFunction) || isa(p.motionFunction, 'function_handle'), ...
    'rotpend:InvalidMotionFunction', ...
    'motionFunction must be empty or a function handle @(t).');
validateProfile(p.alphaProfile, 'alphaProfile');
validateProfile(p.betaProfile, 'betaProfile');
rotpend.motionAt(0, p);
end

function validateProfile(profile, name)
fields = {'initialAngle','meanRate','amplitude','frequency','phase'};
assert(isstruct(profile) && all(isfield(profile, fields)), ...
    'rotpend:InvalidMotionProfile', '%s is incomplete.', name);
for k = 1:numel(fields)
    value = profile.(fields{k});
    assert(isnumeric(value) && isscalar(value) && isfinite(value), ...
        'rotpend:InvalidMotionProfile', ...
        '%s.%s must be a finite scalar.', name, fields{k});
end
assert(profile.frequency >= 0, 'rotpend:InvalidMotionProfile', ...
    '%s.frequency must be nonnegative.', name);
end